### ISSUE TITLE
Is a duplicate a bad thing?

### ISSUE THREAD

**Issue by mark-chief** [putyourlightson/craft-elements-panel#1]
Just trying to work out if a duplicate is a bad thing, is it listed there to show that something should be done? I've been playing around with a static Super Table field and the duplicate value doesn't change. Thanks

**Comment by bencroker** [comment]
A duplicate means that the same element was populated more than once. If you can avoid this by eager-loading or memoizing, then great. If not, then that's probably ok too provided the number of populated elements doesn't explode.

**Comment by jkorff** [comment]
It might make sense to add a bit more in the docs for this feature. I was wondering too a) what a duplicate is b) how they get generated and c) how I can debug and avoid them.

**Comment by bencroker** [comment]
Added to the docs at https://putyourlightson.com/plugins/elements-panel, although there isn't always an obvious reason or solution to duplicates, and sometimes they're just fine to have provided they don't get out of hand.
