### ISSUE TITLE
Craft CMS 5 compatibility

### ISSUE THREAD

**Issue by stevendierick** [putyourlightson/craft-elements-panel#6]
Hey Ben, will you be adding compatibility for Craft CMS 5?

**Comment by bencroker** [comment]
Yes, it’s in the works.

**Comment by bencroker** [comment]
Just released [3.0.0-beta.1](https://github.com/putyourlightson/craft-elements-panel/releases/tag/3.0.0-beta.1) with Craft 5 compatibility.
